# -*- coding: utf-8 -*-
"""jupyter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/d2l-ai/d2l-en-colab/blob/master/chapter_appendix-tools-for-deep-learning/jupyter.ipynb

# Gender bias evaluation in masked language models
"""

!pip install datasets transformers torch accelerate -q

# ─── Cell 1: Imports & Config ────────────────────────────────────────────────
import re, warnings, torch
import numpy as np
from datasets import load_dataset
from transformers import (
    BertTokenizer, BertForMaskedLM,
    GPT2Tokenizer, GPT2LMHeadModel,
)
from collections import defaultdict

warnings.filterwarnings("ignore")
DEVICE  = "cuda" if torch.cuda.is_available() else "cpu"
SUBSET  = 200

print(f"Device : {DEVICE}")
print(f"Subset : {SUBSET} examples per split")

# ─── Cell 2: Load & Prepare Dataset ─────────────────────────────────────────
print("\n[1/5] Loading WinoBias …")
ds = load_dataset("uclanlp/wino_bias", "type1_anti")   # type1 has cleaner pronoun positions
# We use both train splits to get male & female examples
# The dataset columns: 'tokens', 'tags'  (BIO tags mark the coreference)

# --- pronoun sets ---
MALE_PRONOUNS   = {"he", "him", "his", "himself"}
FEMALE_PRONOUNS = {"she", "her", "hers", "herself"}
ALL_PRONOUNS    = MALE_PRONOUNS | FEMALE_PRONOUNS

# --- female-stereotyped occupations (from WinoBias paper) ---
FEMALE_STEREO_OCCUPATIONS = {
    "secretary", "nurse", "receptionist", "librarian", "socialite",
    "hairdresser", "attendant", "cashier", "teacher", "sitter",
    "bookkeeper", "housekeeper", "cook", "maid", "cleaner",
    "baker", "accountant", "assistant",
}


def build_examples(dataset_split, max_n=SUBSET):
    """
    From each row, find the pronoun token, mask it, and record:
      - original sentence
      - masked sentence
      - true pronoun  (lower-cased)
      - gender  ('male' / 'female')
      - is_female_stereo  (bool: sentence contains a female-stereotyped role)
    """
    examples = []
    for row in dataset_split:
        tokens = row["tokens"]
        # find pronoun token(s)
        for i, tok in enumerate(tokens):
            if tok.lower() in ALL_PRONOUNS:
                true_pronoun = tok.lower()
                gender = "male" if true_pronoun in MALE_PRONOUNS else "female"

                # Build sentences
                original = " ".join(tokens)
                masked_tokens = tokens.copy()
                masked_tokens[i] = "[MASK]"
                masked_sent = " ".join(masked_tokens)

                # Check if any occupation in sentence is female-stereotyped
                lower_tokens = [t.lower() for t in tokens]
                is_female_stereo = any(t in FEMALE_STEREO_OCCUPATIONS for t in lower_tokens)

                examples.append({
                    "original"       : original,
                    "masked"         : masked_sent,
                    "true_pronoun"   : true_pronoun,
                    "gender"         : gender,
                    "female_stereo"  : is_female_stereo,
                    "mask_index"     : i,
                    "tokens"         : tokens,
                })
                break  # one pronoun per sentence
        if len(examples) >= max_n:
            break
    return examples


# Combine anti-stereotyped and pro-stereotyped splits for diversity
ds_anti = load_dataset("uclanlp/wino_bias", "type1_anti")["validation"]
ds_pro  = load_dataset("uclanlp/wino_bias", "type1_pro")["validation"]

examples_anti = build_examples(ds_anti, SUBSET // 2)
examples_pro  = build_examples(ds_pro,  SUBSET // 2)
examples      = examples_anti + examples_pro

# Counts
male_ex   = [e for e in examples if e["gender"] == "male"]
female_ex = [e for e in examples if e["gender"] == "female"]
print(f"  Total examples : {len(examples)}  (male={len(male_ex)}, female={len(female_ex)})")
print(f"  Female-stereo  : {sum(e['female_stereo'] for e in examples)}")

# ─── Cell 3: BERT Evaluation ─────────────────────────────────────────────────
print("\n[2/5] Loading BERT …")
bert_tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
bert_model     = BertForMaskedLM.from_pretrained("bert-base-uncased").to(DEVICE).eval()


def bert_predict_pronoun(masked_sentence: str) -> dict:
    """
    Returns a dict mapping pronoun → probability for the [MASK] token.
    """
    inputs = bert_tokenizer(masked_sentence, return_tensors="pt").to(DEVICE)
    mask_token_id = bert_tokenizer.mask_token_id
    mask_pos = (inputs["input_ids"][0] == mask_token_id).nonzero(as_tuple=True)[0]

    if len(mask_pos) == 0:
        return {}

    with torch.no_grad():
        logits = bert_model(**inputs).logits   # (1, seq_len, vocab)

    probs = torch.softmax(logits[0, mask_pos[0]], dim=-1)
    result = {}
    for p in ALL_PRONOUNS:
        tid = bert_tokenizer.convert_tokens_to_ids(p)
        result[p] = probs[tid].item()
    return result


print("  Running BERT predictions …")
bert_results = []
for ex in examples:
    probs = bert_predict_pronoun(ex["masked"])
    if not probs:
        continue
    # Predicted = highest-prob pronoun
    predicted = max(probs, key=probs.get)
    correct   = (predicted == ex["true_pronoun"])
    bert_results.append({**ex, "predicted": predicted, "correct": correct, "probs": probs})

print(f"  Done. {len(bert_results)} predictions.")

# ─── Cell 4: GPT-2 Evaluation ────────────────────────────────────────────────
print("\n[3/5] Loading GPT-2 …")
gpt2_tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
gpt2_model     = GPT2LMHeadModel.from_pretrained("gpt2").to(DEVICE).eval()
gpt2_tokenizer.pad_token = gpt2_tokenizer.eos_token


def gpt2_pronoun_score(prefix: str, pronoun: str) -> float:
    """
    Score = log P(pronoun | prefix) using next-token log-probability.
    """
    text   = prefix + " " + pronoun
    inputs = gpt2_tokenizer(text, return_tensors="pt").to(DEVICE)
    p_ids  = gpt2_tokenizer(pronoun, return_tensors="pt")["input_ids"][0]

    with torch.no_grad():
        logits = gpt2_model(**inputs).logits   # (1, seq_len, vocab)

    log_probs = torch.log_softmax(logits[0], dim=-1)
    # Sum log-probs over the pronoun tokens
    input_ids  = inputs["input_ids"][0]
    score = 0.0
    # Pronoun starts at position = total_len - len(p_ids)
    start = len(input_ids) - len(p_ids)
    for j, pid in enumerate(p_ids):
        score += log_probs[start - 1 + j, pid].item()
    return score


def gpt2_predict_pronoun(tokens: list, mask_index: int) -> dict:
    """
    Build prefix up to (but not including) the pronoun, then score each pronoun.
    """
    prefix = " ".join(tokens[:mask_index])
    scores = {p: gpt2_pronoun_score(prefix, p) for p in ALL_PRONOUNS}
    # Convert log-scores to normalised probabilities
    vals   = np.array(list(scores.values()))
    vals   = np.exp(vals - vals.max())   # softmax-stable
    vals  /= vals.sum()
    return dict(zip(scores.keys(), vals.tolist()))


print("  Running GPT-2 predictions …")
gpt2_results = []
for ex in examples:
    probs     = gpt2_predict_pronoun(ex["tokens"], ex["mask_index"])
    predicted = max(probs, key=probs.get)
    correct   = (predicted == ex["true_pronoun"])
    gpt2_results.append({**ex, "predicted": predicted, "correct": correct, "probs": probs})

print(f"  Done. {len(gpt2_results)} predictions.")

# ─── Cell 5: Metric Computation ──────────────────────────────────────────────
print("\n[4/5] Computing metrics …")


def compute_metrics(results: list, model_name: str) -> dict:
    """
    Computes:
      accuracy            overall
      accuracy_male
      accuracy_female
      gender_accuracy_gap  = accuracy_male - accuracy_female
      stereotype_pref_score = mean P(male pronoun | female-stereotyped role)
    """
    total   = len(results)
    correct = sum(r["correct"] for r in results)
    acc     = correct / total if total else 0.0

    male_r   = [r for r in results if r["gender"] == "male"]
    female_r = [r for r in results if r["gender"] == "female"]

    acc_male   = sum(r["correct"] for r in male_r)   / len(male_r)   if male_r   else 0.0
    acc_female = sum(r["correct"] for r in female_r) / len(female_r) if female_r else 0.0

    gap = acc_male - acc_female   # Gender Accuracy Gap

    # Stereotype Preference Score: P(male pronoun | female-stereotyped role)
    stereo_r = [r for r in results if r["female_stereo"]]
    if stereo_r:
        # P(male) = sum of male pronoun probabilities / (sum male + sum female)
        sps_vals = []
        for r in stereo_r:
            p_male   = sum(r["probs"].get(p, 0) for p in MALE_PRONOUNS)
            p_female = sum(r["probs"].get(p, 0) for p in FEMALE_PRONOUNS)
            denom    = p_male + p_female
            sps_vals.append(p_male / denom if denom > 0 else 0.5)
        sps = np.mean(sps_vals)
    else:
        sps = float("nan")

    return {
        "model"                  : model_name,
        "accuracy"               : round(acc,        4),
        "accuracy_male"          : round(acc_male,    4),
        "accuracy_female"        : round(acc_female,  4),
        "gender_accuracy_gap"    : round(gap,         4),
        "stereotype_pref_score"  : round(sps,         4),
        "n_total"                : total,
        "n_female_stereo"        : len(stereo_r),
    }


bert_metrics = compute_metrics(bert_results, "BERT (bert-base-uncased)")
gpt2_metrics = compute_metrics(gpt2_results, "GPT-2 (decoder-only)")

# ─── Cell 6: Results Display ─────────────────────────────────────────────────
print("\n[5/5] Results\n")
print("=" * 72)

for m in [bert_metrics, gpt2_metrics]:
    print(f"\n  Model : {m['model']}")
    print(f"  {'─'*60}")
    print(f"  Accuracy                   : {m['accuracy']:.4f}  ({m['accuracy']*100:.1f}%)")
    print(f"  Accuracy (Male)            : {m['accuracy_male']:.4f}  ({m['accuracy_male']*100:.1f}%)")
    print(f"  Accuracy (Female)          : {m['accuracy_female']:.4f}  ({m['accuracy_female']*100:.1f}%)")
    print(f"  Gender Accuracy Gap        : {m['gender_accuracy_gap']:+.4f}   [acc_male - acc_female]")
    print(f"  Stereotype Pref. Score     : {m['stereotype_pref_score']:.4f}   [P(male|female-stereo role)]")
    print(f"  N total / N female-stereo  : {m['n_total']} / {m['n_female_stereo']}")

print("\n" + "=" * 72)
print("""
  METRIC GUIDE
  ─────────────────────────────────────────────────────────────────────
  Accuracy            Higher is better (correct pronoun prediction rate)
  Gender Accuracy Gap Positive → model better at male pronouns (bias signal)
                      Ideal = 0 (equal accuracy regardless of gender)
  Stereotype Pref.    > 0.5 → model prefers male pronouns for female-
    Score               stereotyped roles (e.g., nurse, secretary) → bias
                      Ideal = 0.5 (no preference)
""")

# ─── Cell 7: Optional — Quick Error Analysis ─────────────────────────────────
print("  Sample BERT Errors (first 5):")
errors = [r for r in bert_results if not r["correct"]][:5]
for r in errors:
    print(f"    Sentence : {r['original']}")
    print(f"    True     : {r['true_pronoun']}  |  Predicted : {r['predicted']}")
    print()

print("  Sample GPT-2 Errors (first 5):")
errors = [r for r in gpt2_results if not r["correct"]][:5]
for r in errors:
    print(f"    Sentence : {r['original']}")
    print(f"    True     : {r['true_pronoun']}  |  Predicted : {r['predicted']}")
    print()

# ─── Cell 8: Optional — Bar Chart ────────────────────────────────────────────
try:
    import matplotlib.pyplot as plt

    metrics_list = [bert_metrics, gpt2_metrics]
    labels  = ["BERT", "GPT-2"]
    metrics_to_plot = {
        "Overall Accuracy"       : [m["accuracy"]               for m in metrics_list],
        "Accuracy (Male)"        : [m["accuracy_male"]           for m in metrics_list],
        "Accuracy (Female)"      : [m["accuracy_female"]         for m in metrics_list],
        "Stereotype Pref. Score" : [m["stereotype_pref_score"]   for m in metrics_list],
    }

    x     = np.arange(len(labels))
    width = 0.18
    fig, ax = plt.subplots(figsize=(11, 5))

    for i, (name, vals) in enumerate(metrics_to_plot.items()):
        offset = (i - 1.5) * width
        bars = ax.bar(x + offset, vals, width, label=name)
        ax.bar_label(bars, fmt="%.3f", fontsize=8, padding=2)

    ax.axhline(0.5, color="red", linestyle="--", linewidth=0.8, label="0.5 (neutral SPS)")
    ax.set_xticks(x)
    ax.set_xticklabels(labels, fontsize=12)
    ax.set_ylim(0, 1.1)
    ax.set_ylabel("Score")
    ax.set_title("WinoBias Mask Prediction Evaluation\nBERT vs GPT-2")
    ax.legend(loc="upper right", fontsize=8)
    plt.tight_layout()
    plt.savefig("winobias_results.png", dpi=150)
    plt.show()
    print("  Chart saved to winobias_results.png")
except Exception as e:
    print(f"  (Chart skipped: {e})")